
spring.data.mongodb.uri = mongodb+srv://karmakarsouvikwork_db_user:HAgG5QuGwnViAB0n@cluster0.zji2m8i.mongodb.net/?appName=Cluster0
#spring.data.mongodb.host = localhost
#spring.data.mongodb.port = 27017
spring.data.mongodb.database = journalDb
spring.data.mongodb.auto-index-creation = true
#spring.data.mongodb.username = myjournaluser
#spring.data.mongodb.password = mypassword